version: '3.8'

services:
  # Development Flask application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: it-asset-manager-dev
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SECRET_KEY=dev-secret-key-change-in-production
      - DATABASE_URL=sqlite:///instance/it_assets.db
    volumes:
      # Mount source code for development
      - .:/app
      # Persist SQLite database
      - sqlite_data:/app/instance
      # Persist logs
      - ./logs:/app/logs
      # Persist uploads
      - ./uploads:/app/uploads
    networks:
      - it-asset-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  sqlite_data:
    driver: local

networks:
  it-asset-network:
    driver: bridge
