title: "💡 [IDEA] "
labels: ["idea"]
body: |
  ## 💡 Idea Summary
  <!-- Brief description of your idea -->

  ## 🎯 Problem or Opportunity
  <!-- What problem does this solve or what opportunity does it create? -->

  ## 💭 Proposed Solution
  <!-- How would you implement this idea? -->

  ## 🌟 Benefits
  <!-- What benefits would this bring to users? -->

  ## 🤔 Considerations
  <!-- Any challenges or considerations to think about? -->

  ## 📊 Community Input
  <!-- What feedback or input would you like from the community? -->
